### ISSUE TITLE
Fast publisher slow subscriber solution isn't parallel

### ISSUE THREAD

**Issue by swayam18** [reactor/lite-rx-api-hands-on#22]
The solution for Part11-Blocking to Reactive solution does not really process the users in parallel. If the intent of the problem is to do the save operations in parallel, I believe this is what the code should look like:

```
Mono<Void> fluxToBlockingRepository(Flux<User> flux, BlockingRepository<User> repository) {
  return flux
    .parallel(8)
    .runOn(Schedulers.parallel())
    .doOnNext(repository::save)
    .sequential().then();
}
```

Or is the intent of the problem to just save users to the repository in a different thread from the main thread, without making it parallel? If so, why is `Schedulers.parallel` recommended over `Schedulers.elastic`?

Thank you!

**Comment by smaldini** [comment]
You are correct, parallel in that case is only used to jump thread. It does tolerate slower execution (and so slower doOnNext in the example) but very blocking or permanently slower downstream flows should use a code similar to yours.

Also its part of a generic question, how do you parallelize your work: by Subscriber (subscribe N times), by CPU (flux.parallel(xx)), by volume (window), by consistent hash (groupBy) or by arbitrary combinations (flatMap/concatMap/zip/).

**Comment by swayam18** [comment]
Alright, fair enough thank you!
