### ISSUE TITLE
Reactor 3.0.6 update

### ISSUE THREAD

**Issue by bclozel** [reactor/lite-rx-api-hands-on#32]
An update to Reactor 3.0.6 apparently [breaks Part 11](https://gitter.im/reactor/reactor?at=58e575a7408f90be66915a05).

It seems the choice of the parallel scheduler is not the right one, since it's designed for CPU-bound tasks. In that case , an elastic Scheduler (for blocking) operations is a better choice.

**Comment by simonbasle** [comment]
Fixed by 4c688ab378a07adafd68bd40494a28ab4fc2e843
