### ISSUE TITLE
Could not find the artifact `reactor-bom:pom:Bismuth-BUILD-SNAPSHOT`

### ISSUE THREAD

**Issue by sedooe** [reactor/lite-rx-api-hands-on#39]
Hi,

With the change in `pom.xml` on f8f68da0be7d01d01580515142c41cecdd61cacb, build fails since it can not find the artifact `io.projectreactor:reactor-bom:pom:Bismuth-BUILD-SNAPSHOT`.

Builds successfully when I revert the previous version of `pom.xml`.

> [INFO] Scanning for projects...
Downloading: https://repo.spring.io/milestone/io/projectreactor/reactor-bom/Bismuth-BUILD-SNAPSHOT/maven-metadata.xml
Downloading: https://repo.spring.io/milestone/io/projectreactor/reactor-bom/Bismuth-BUILD-SNAPSHOT/reactor-bom-Bismuth-BUILD-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact io.projectreactor:reactor-bom:pom:Bismuth-BUILD-SNAPSHOT in spring-milestones (https://repo.spring.io/milestone) @ line 92, column 16
[ERROR] 'dependencies.dependency.version' for io.projectreactor:reactor-core:jar is missing. @ line 35, column 15
[ERROR] 'dependencies.dependency.version' for io.projectreactor:reactor-test:jar is missing. @ line 39, column 15
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.pivotal:lite-rx-api-hands-on:1.1.0-SNAPSHOT (/home/sedat/Desktop/code/lite-rx-api-hands-on/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Could not find artifact io.projectreactor:reactor-bom:pom:Bismuth-BUILD-SNAPSHOT in spring-milestones (https://repo.spring.io/milestone) @ line 92, column 16 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for io.projectreactor:reactor-core:jar is missing. @ line 35, column 15
[ERROR]     'dependencies.dependency.version' for io.projectreactor:reactor-test:jar is missing. @ line 39, column 15
[ERROR]

**Comment by smaldini** [comment]
That's right actually we should even use M2 now. Will look at it at the office

**Comment by smaldini** [comment]
Fixed to M2
