### ISSUE TITLE
Update Bismuth release

### ISSUE THREAD

**Issue by smaldini** [reactor/lite-rx-api-hands-on#44]

**Comment by simonbasle** [comment]
There was an update on the master branch but not the complete branch, will need a bit of rebasing magic. Update to SR3 just need to replace `firstEmitting` to `first`.

**Comment by sdeleuze** [comment]
Done via d400589055024cdd41db4b6bbfe46000e3d1c1ef and cf4ff2177f94871e94cc33d509ad6a084bd6390a.
