### ISSUE TITLE
Part08OtherOperationsTest#complete() can also be satisfied with Mono.empty()

### ISSUE THREAD

**Issue by h2m** [reactor/lite-rx-api-hands-on#47]
Salut @sdeleuze,

how can the test Part08OtherOperationsTest#complete() be improved to check as well that the original flux is completed, which is signaled by the Mono? Because the current test is already happy with Mono.empty().

Best Marc

**Comment by h2m** [comment]
@sdeleuze Merci! PublisherProbe was the missing thing. I initially thought I could get that assertion just with the original flux.

**Comment by sdeleuze** [comment]
Kudos to @simonbasle for the hint ;-)
