### ISSUE TITLE
Part 08's GetOutOfHereException has no definition of serialVersionUID

### ISSUE THREAD

**Issue by dmedinag** [reactor/lite-rx-api-hands-on#53]
Due to this, a warning is raised when following the tutorial (fixed in this [PR](https://github.com/dmedinag/lite-rx-api-hands-on/tree/patch-1) as seen in [here](https://stackoverflow.com/questions/7823477/warning-serial-serializable-class-someclass-has-no-definition-of-serialversio) )

**Comment by PyvesB** [comment]
This issue can probably now be closed given that the linked PR has been merged. 😉
