### ISSUE TITLE
Add `Flux.collect...()` method exercise

### ISSUE THREAD

**Issue by paweusz** [reactor/lite-rx-api-hands-on#75]
## Motivation

As currently there's no exercise for `Flux.collect...()` methods I thought that at least one case could be helpful.

## Desired solution

I'd like to add method testing `Flux.collectList()`:

```java
	// TODO Convert the input Flux<User> to a Mono<List<User>> containing list of collected flux values
	Mono<List<User>> fluxCollection(Flux<User> flux) {
		return flux.collectList(); // TO BE REMOVED
	}
```

to `Part08OtherOperations` class.

## Considered alternatives

Adding entire family of `Flux.collect...()` methods would be probably overkill.
One should be enough to signal existence of those.

**Comment by simonbasle** [comment]
👍 yeah and I agree, focusing on `collectList()` (and maybe mentioning that there are variants in the markdown course on `techio_course` branch) would suffice
