### ISSUE TITLE
NCDFE: org/junit/runner/notification/RunListener on https://tech.io/playgrounds/929/reactive-programming-with-reactor-3

### ISSUE THREAD

**Issue by pascalleclercq** [reactor/lite-rx-api-hands-on#80]
Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/runner/notification/RunListener
while using https://tech.io/playgrounds/929/reactive-programming-with-reactor-3/Flux

## Expected Behavior
I would like to be able to play with https://tech.io/playgrounds/929/reactive-programming-with-reactor-3/

## Actual Behavior
while submitting "Run" on any button of https://tech.io/playgrounds/929/reactive-programming-with-reactor-3/Flux a NCDFE "org/junit/runner/notification/RunListener " this make the tutorial almost unusable.

## Steps to Reproduce
https://tech.io/playgrounds/929/reactive-programming-with-reactor-3/Flux and click on any "Run" button

## Possible Solution
I suspect the runner https://github.com/TechDotIO/java-maven3-junit4-runner is used for this project but junit 4 class doesn't exists anymore on https://github.com/reactor/lite-rx-api-hands-on/tree/techio_course this lead to the NCDFE

I suspect this is due to https://github.com/reactor/lite-rx-api-hands-on/pull/71

Possible solutions : 
- add junit4 jar as a dependency of the project
- revert the PR on the "techio_course" branch.
- provide a java-maven3-junit4-runner to https://github.com/TechDotIO

**Comment by simonbasle** [comment]
thanks for reporting, I'll look into using the base `maven3` runner

**Comment by simonbasle** [comment]
Fixed in 5855d0e
