### ISSUE TITLE
Part06Request fluxWithDoOnPrintln failing due to logger

### ISSUE THREAD

**Issue by govi20** [reactor/lite-rx-api-hands-on#81]
## Expected Behavior

Below `fluxWithDoOnPrintln` implementation is failing due to a logger statement. The logger is appending the below line to the console.

DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework

```
Flux<User> fluxWithDoOnPrintln() {
	return repository.findAll().doOnSubscribe(a -> System.out.println("Starring:"))
			.doOnNext(user -> System.out.println(String.format("%s %s", user.getFirstname(), user.getLastname())))
			.doOnComplete(() -> System.out.println("The end!")); //TODO: Disable logger
}
```

Logs:

```
org.opentest4j.AssertionFailedError: 
Expecting:
 <"21:18:16.820 [main] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
Starring:
Skyler White
Jesse Pinkman
Walter White
Saul Goodman
The end!
">
to be equal to:
 <"Starring:
Skyler White
Jesse Pinkman
Walter White
Saul Goodman
The end!
">

```

**Comment by simonbasle** [comment]
Deployed on tech.io 👍

**Comment by govi20** [comment]
Seems https://www.codingame.com/playgrounds/929/reactive-programming-with-reactor-3/Flux is also using it.

This is really handy repository to understand and practice reactive programming. Thank you guys!
